version: '3'

services:
  web-backend:
    container_name: car-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
      ASPNETCORE_URLS: http://0.0.0.0:8080

  db:
    image: postgres
    restart: always
    container_name: postgres_db_web
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
 